import 'normalize.css';
import './styles.css';
import LinkedList from './linkedList';

const list = new LinkedList;

console.log('----');
console.log(`Created empty list: ${list.toString()}`);
console.log('----');
console.log('Testing .prepend()')
list.prepend(1);
console.log(`prepend "1": ${list.toString()}`);
list.prepend(3);
console.log(`prepend "3": ${list.toString()}`);
console.log('----');
console.log('Testing .append()');
list.append(10);
console.log(`append "10": ${list.toString()}`);
list.append(5);
console.log(`append "5": ${list.toString()}`);
console.log('----');
console.log('Testing .size()');
console.log(`list size: ${list.size()}`);
console.log('----');
console.log('Testing .head()');
console.log(`list head: ${list.head().value}`);
console.log('----');
console.log('Testing .tail()');
console.log(`list tail: ${list.tail().value}`);
console.log('----');
console.log('Testing .at()');
console.log(`value at "0": ${list.at(0).value}`);
console.log(`value at "2": ${list.at(2).value}`);
console.log(`value at "10": ${list.at(10)}`);
console.log('----');
console.log('Testing .pop()');
console.log(`initial list: ${list.toString()}`);
list.pop();
console.log(`list after .pop(): ${list.toString()}`);
console.log('----');
console.log('Testing .find()');
console.log(`initial list: ${list.toString()}`);
console.log(`find "10": ${list.find(10)}`);
console.log(`find "11": ${list.find(11)}`);
console.log('----');
console.log('Testing .contains()');
console.log(`initial list: ${list.toString()}`);
console.log(`contains "10": ${list.contains(10)}`);
console.log(`contains "11": ${list.contains(11)}`);
console.log('----');
console.log('Testing .insertAt()');
console.log(`initial list: ${list.toString()}`);
list.insertAt(13, 1);
console.log(`insert "13" at "1": ${list.toString()}`);
list.insertAt(66, 10);
console.log(`insert "66" at "10": ${list.toString()}`);
console.log('----');
console.log('Testing .removeAt()');
console.log(`initial list: ${list.toString()}`);
list.removeAt(3);
console.log(`remove at "3": ${list.toString()}`);
list.removeAt(2);
console.log(`remove at "2": ${list.toString()}`);
list.removeAt(10);
console.log(`remove at "10": ${list.removeAt(10)}`);